### ISSUE TITLE
ООО "ИСС Арт"

### ISSUE THREAD

**Issue by imoiseyev** [Mary-Ya/Tetris#6]
Добрый день. Меня зовут Моисеев Иван. Я являюсь менеджером по персоналу компании "ИСС Арт". Нашли Ваше резюме на сайте НН и решили обратиться к Вам. В нашей компании открыта вакансия JS разработчика. Рассматриваете ли Вы предложения по работе? От какой суммы рассматриваете предложения? 
Отправьте пожалуйста код на JS  с замыканием классов. Можете написать на mail: ivan_moiseyev@issart.com
Благодарю.

**Comment by Mary-Ya** [comment]
Здравствуйте, Иван. 
Ответила на почту.
